# --- Site settings (you can personalize titles later) ---
title: Jamie Nam
SEOTitle: Jamie Nam | Research & Notes
header-img: img/home-bg.jpg
email: your.email@example.com
description: "Research notes, projects, and lab updates."
keyword: "Jamie Nam, research, HCI, digital health, IS"
url: "https://jamienam.github.io"   # IMPORTANT: your real site URL
baseurl: ""                         # user sites keep this empty

future: true

# --- Social (update as you like) ---
RSS: false
weibo_username:
zhihu_username:
github_username: jamienam
twitter_username:
#facebook_username:
#linkedin_username:

# --- Build settings ---
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  - less
  - node_modules
  - Gruntfile.js
  - package.json
  - README.md
  - README.zh.md
anchorjs: true
# timezone: America/Toronto    # uncomment if you want local times

plugins:
  - jekyll-paginate            # allowed on GitHub Pages

# --- Markdown ---
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# --- Comments/Analytics (off for now) ---
disqus_username:
netease_comment: false
ga_track_id: ""                 # UA is deprecated; leave blank or add GA4 via custom include
ga_domain:

# --- Sidebar ---
sidebar: true
sidebar-about-description: "Notes from the workbench."
sidebar-avatar: https://avatars.githubusercontent.com/u/00000000?v=4  # replace with your avatar URL

# --- Featured Tags ---
featured-tags: true
featured-condition-size: 1

# --- PWA ---
chrome-tab-theme-color: "#000000"
service-worker: true

# --- Math (optional per-page) ---
page-mathjax: false

# --- Friends (optional) ---
friends: []

